### ISSUE TITLE
Torcx is deprecated

### ISSUE THREAD

**Issue by paour** [mback2k/torcx-htop#1]
Have you seen this deprecation notice? https://www.flatcar.org/docs/latest/provisioning/torcx/#deprecation-notice

I'm in the process of migrating my other torcx modules to the new format. Do you have similar plans?

**Comment by mback2k** [comment]
Thanks for the heads-up. I am starting the migration of my torcx packages now.

**Comment by mback2k** [comment]
Migration complete.

**Comment by paour** [comment]
Thank you. If you don't mind, I'll use the same approach (blatantly copy) to upgrade my own modules :-).
